### PR TITLE
add HW2

### PR DESCRIPTION
**Pull request by Dywei126**
homework2 from Dongyu Wei

### CODE REVIEW

**Comment by AlexanderPolus** [comment]
Please check how you added your files - it appears you've create a conflict with the HW2 folder and I can't merge this or see your submission

**Comment by Dywei126** [comment]
Sorry Alex, I just saw your email. I create a branch called hw_2_Dongyu_Wei
and submit my hw2. should I create a new branch and submit this again?

Best regards,
Dongyu Wei.

Alex Polus ***@***.***> 于2022年1月17日周一 12:02写道：

**Comment by Dywei126** [comment]
> Please check how you added your files - it appears you've create a conflict with the HW2 folder and I can't merge this or see your submission

**Comment by Dywei126** [comment]
> Please check how you added your files - it appears you've create a conflict with the HW2 folder and I can't merge this or see your submission

I don't know what I've done to cause the conflict and I don't know how to fix it. I guess the reason could be the repository of my branches. Can I resubmit this pull request?

**Comment by Dywei126** [comment]
Hi,Alex. I have submitted my homework2 again. I hope it could work and
won't cause any conflict. If there is any other problem, just contact me!

Best regards,
DongyuWei

Alex Polus ***@***.***> 于2022年1月17日周一 12:02写道：

**Pull request closed without merging**
